name: 'Download Artifact from Azure DevOps'
description: 'Download build artifact from Azure DevOps'
author: 'Manish Satwani'
inputs:
  buildDefinitionId:
    description: 'Build Definition Id for which the artifact is going to be downloaded'
  pattoken:
    description: 'PAT token to access build and build artifacts'
  artifactName: 
    description: 'Name of the artifact'
  orgName:
    description: 'Azure DevOps organization name'
  projectId:
    description: 'Azure DevOps projectId for which the build and artifacts belongs to'
branding:
  icon: 'download-cloud'
  color: 'blue'
runs:
  using: 'node12'
  main: 'lib/main.js'
